apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nginx-helm-operator.fullname" . }}-controller-manager
  namespace: {{ include "nginx-helm-operator.namespaceName" . }}
  labels:
    {{- include "nginx-helm-operator.labels" . | nindent 4 }}
    control-plane: controller-manager
    app.kubernetes.io/component: manager
  annotations:
    {{- include "nginx-helm-operator.annotations" . | nindent 4 }}
    {{- with .Values.podAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.operator.replicaCount }}
  selector:
    matchLabels:
      {{- include "nginx-helm-operator.selectorLabels" . | nindent 6 }}
      control-plane: controller-manager
  template:
    metadata:
      labels:
        {{- include "nginx-helm-operator.selectorLabels" . | nindent 8 }}
        control-plane: controller-manager
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        kubectl.kubernetes.io/default-container: manager
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- include "nginx-helm-operator.imagePullSecrets" . | nindent 6 }}
      serviceAccountName: {{ include "nginx-helm-operator.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.operator.securityContext | nindent 8 }}
      containers:
      - name: manager
        image: {{ include "nginx-helm-operator.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        securityContext:
          {{- toYaml .Values.operator.containerSecurityContext | nindent 10 }}
        command:
        - /manager
        args:
        {{- if .Values.leaderElection.enabled }}
        - --leader-elect
        {{- end }}
        {{- if .Values.metrics.enabled }}
        - --metrics-bind-address={{ .Values.metrics.bindAddress }}:{{ .Values.metrics.port }}
        {{- else }}
        - --metrics-bind-address=0
        {{- end }}
        {{- if .Values.healthCheck.enabled }}
        - --health-probe-bind-address=:{{ .Values.healthCheck.port }}
        {{- end }}
        env:
        - name: HELM_CHARTS_PATH
          value: "/charts"
        {{- with .Values.env }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        ports:
        {{- if .Values.metrics.enabled }}
        - containerPort: {{ .Values.metrics.port }}
          name: metrics
          protocol: TCP
        {{- end }}
        {{- if .Values.healthCheck.enabled }}
        - containerPort: {{ .Values.healthCheck.port }}
          name: health
          protocol: TCP
        {{- end }}
        {{- if .Values.webhook.enabled }}
        - containerPort: {{ .Values.webhook.service.port }}
          name: webhook-server
          protocol: TCP
        {{- end }}
        {{- if .Values.healthCheck.enabled }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: health
          {{- toYaml .Values.healthCheck.livenessProbe | nindent 10 }}
        readinessProbe:
          httpGet:
            path: /readyz
            port: health
          {{- toYaml .Values.healthCheck.readinessProbe | nindent 10 }}
        {{- end }}
        resources:
          {{- toYaml .Values.operator.resources | nindent 10 }}
        volumeMounts:
        {{- if .Values.webhook.enabled }}
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
        {{- end }}
        {{- with .Values.volumeMounts }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      volumes:
      {{- if .Values.webhook.enabled }}
      - name: cert
        secret:
          defaultMode: 420
          secretName: {{ include "nginx-helm-operator.fullname" . }}-webhook-server-cert
      {{- end }}
      {{- with .Values.volumes }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.operator.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.operator.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.operator.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: 10