{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nginx-helm-operator.serviceAccountName" . }}
  namespace: {{ include "nginx-helm-operator.namespaceName" . }}
  labels:
    {{- include "nginx-helm-operator.labels" . | nindent 4 }}
  annotations:
    {{- include "nginx-helm-operator.annotations" . | nindent 4 }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
automountServiceAccountToken: true
{{- end }}